name: opa-fmt
description: opa fmt action
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: true
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/github-action-format@v0.1.1
      with:
        github_token: ${{ inputs.github_token }}
        command: git ls-files | grep -E "\.rego$" | xargs opa fmt -l && git ls-files | grep -E "\.rego$" | xargs opa fmt -w
        commit_message: "style: opa fmt"
